#!/system/bin/sh

# Since we gonna check lots of files existence 
function nex () {
	if [ -e $1 -a -w $1 ]; then
	echo $2 > $1
	fi
}

# Kernel
nex /proc/sys/kernel/sched_child_runs_first 1
nex /proc/sys/kernel/timer_migration 1
nex /proc/sys/kernel/perf_cpu_time_max_percent 90
nex /proc/sys/kernel/sched_min_granularity_ns 1000000
nex /proc/sys/kernel/sched_migration_cost_ns 500000
nex /proc/sys/kernel/sched_nr_migrate 32

# Fs
nex /proc/sys/fs/lease-break-time 50

# VM
nex /proc/sys/vm/stat_interval 60
nex /proc/sys/vm/vfs_cache_pressure 24
nex /proc/sys/vm/swappiness 60

# Stuneboost
nex /dev/stune/top-app/schedtune.boost 1
nex /dev/stune/foreground/schedtune.boost 0
nex /dev/stune/top-app/schedtune.prefer_idle 0

# EAS
nex /proc/sys/kernel/sched_energy_aware 1

# CPU
nex /sys/module/cpu_input_boost/parameters/input_boost_duration 0

# spi CRC
nex /sys/module/mmc_core/parameters/use_spi_crc 1

# GPU
nex /sys/class/kgsl/kgsl-3d0/devfreq/adrenoboost 0

# adreno idler
nex /sys/module/adreno_idler/parameters/adreno_idler_active 1
nex /sys/module/adreno_idler/parameters/adreno_idler_downdifferential 64
nex /sys/module/adreno_idler/parameters/adreno_idler_idlewait 5
nex /sys/module/adreno_idler/parameters/adreno_idler_idleworkload 7000

nex /sys/class/kgsl/kgsl-3d0/devfreq/polling_interval 16

nex /sys/class/kgsl/kgsl-3d0/throttling 1
nex /sys/class/kgsl/kgsl-3d0/force_clk_on 0
nex /sys/class/kgsl/kgsl-3d0/force_bus_on 0
nex /sys/class/kgsl/kgsl-3d0/force_rail_on 0
nex /sys/class/kgsl/kgsl-3d0/force_no_nap 0
nex /sys/class/kgsl/kgsl-3d0/bus_split 1

nex /sys/class/kgsl/kgsl-3d0/dispatch/inflight 15
nex /sys/class/kgsl/kgsl-3d0/dispatch/inflight_low_latency 4

# Schedutil Bess
nex /sys/devices/system/cpu/cpu0/cpufreq/schedutil/down_rate_limit_us 2000
nex /sys/devices/system/cpu/cpu4/cpufreq/schedutil/down_rate_limit_us 2000
nex /sys/devices/system/cpu/cpu0/cpufreq/schedutil/iowait_boost_enable 0
nex /sys/devices/system/cpu/cpu4/cpufreq/schedutil/iowait_boost_enable 0
nex /sys/devices/system/cpu/cpu0/cpufreq/schedutil/up_rate_limit_us 500
nex /sys/devices/system/cpu/cpu4/cpufreq/schedutil/up_rate_limit_us 500

# block
for queue in /sys/block/*/queue
do
echo 128 > "${queue}"/nr_requests
echo 0 > "${queue}"/rq_affinity
echo 0 > "${queue}"/nomerges
done

# Notify nexus deamon know that we're done here
resetprop nex.profile 0
sed -i '/nex.profile=/s/.*/nex.profile=0/' /data/adb/modules/nexus/system.prop

