#!/system/bin/sh

if [ "$(getprop nex.dus)" == "0" ]; then
status=enable
else
status=disable
fi

# Disable Unnecessary Services (DUS)
pm $status mobi.lockdown.weather/com.google.android.gms.measurement.AppMeasurementService
pm $status com.whatsapp/com.whatsapp.notification.AndroidWear
pm $status com.google.android.soundpicker/com.google.android.gms.measurement.AppMeasurementService
pm $status com.android.vending/com.google.android.finsky.wearsupport.WearSupportService
pm $status com.android.vending/com.google.android.finsky.wearsupport.WearChangeListenerService
pm $status com.android.vending/com.google.android.finsky.instantapps.InstantAppHygieneService
pm $status com.android.vending/com.google.android.finsky.instantapps.InstantAppsSharedPreferencesService
pm $status com.android.vending/com.google.android.finsky.instantapps.launchservice.InstantAppsLaunchService
pm $status com.android.vending/com.google.android.finsky.ipcservers.instantapps.InstantAppsGrpcServerAndroidService
pm $status com.motorola.faceunlock/com.motorola.faceunlock.service.FaceAuthService
pm $status org.adaway/androidx.work.impl.background.systemalarm.SystemAlarmService
pm $status com.android.printspooler/com.android.printspooler.model.PrintSpoolerService
pm $status com.google.android.dialer/com.google.firebase.messaging.FirebaseMessagingService
pm $status com.android.bips/com.android.bips.BuiltInPrintService
pm $status com.google.android.syncadapters.contacts/com.google.android.syncadapters.contacts.ContactsSyncAdapterService
pm $status com.google.android.syncadapters.contacts/com.google.android.gms.analytics.AnalyticsService
pm $status com.google.android.calculator/com.google.android.gms.measurement.AppMeasurementService
pm $status org.nad.ota/org.nad.ota.controller.UpdaterService
pm $status org.nad.ota/org.nad.ota.ExportUpdateService
pm $status com.android.printservice.recommendation/com.android.printservice.recommendation.RecommendationServiceImpl
pm $status com.android.gallery3d/com.android.gallery3d.gadget.WidgetService
pm $status com.facebook.katana/com.facebook.analytics.appstatelogger.AppStateIntentService
pm $status com.facebook.orca/com.facebook.analytics.apptatelogger.AppStateIntentService
pm $status com.facebook.orca/com.facebook.analytics2.Logger.LollipopUploadService
pm $status com.google.android.gms/.chimera.GmsIntentOperationService
pm $status com.google.android.gms/com.google.android.gms.analytics.service.AnalyticsService
pm $status com.google.android.gms/com.google.android.gms.analytics.AnalyticsService
pm $status com.google.android.gms/com.google.android.gms.appstate.service.AppStateSyncService
pm $status com.google.android.gms/com.google.android.gms.auth.account.authenticator.WorkAccountAuthenticatorService
pm $status com.google.android.gms/com.google.android.gms.auth.proximity.BluetoothListenerService
pm $status com.google.android.gms/com.google.android.gms.auth.proximity.BluetoothInitiatorService
pm $status com.google.android.gms/com.google.android.gms.checkin.EventLogService
pm $status com.google.android.gms/com.google.android.gms.drive.metadata.sync.syncadapter.MetadataSyncService
pm $status com.google.android.gms/com.google.android.gms.feedback.FeedbackAsyncService
pm $status com.google.android.gms/com.google.android.gms.fitness.sync.FitnessSyncAdapterService
pm $status com.google.android.gms/com.google.android.gms.fitness.wearables.WearableSyncService
pm $status com.google.android.gms/com.google.android.gms.fitness.service.wearable.WearableSyncMessageService
pm $status com.google.android.gms/com.google.android.gms.fitness.service.wearable.WearableSyncAccountService
pm $status com.google.android.gms/com.google.android.gms.fitness.service.wearable.WearableSyncConnectionService
pm $status com.google.android.gms/com.google.android.gms.fitness.service.wearable.WearableSyncConfigService
pm $status com.google.android.gms/com.google.android.gms.instantapps.service.InstantAppsService
pm $status com.google.android.gms/com.google.android.gms.kids.SupervisionService
pm $status com.google.android.gms/com.google.android.location.reporting.service.ReportingSyncService
pm $status com.google.android.gms/com.google.android.location.wearable.WearableLocationService
pm $status com.google.android.gms/com.google.android.location.drivingmode.AutoLaunchService
pm $status com.google.android.gms/com.google.android.location.service.EAlertSettingInjectorService
pm $status com.google.android.gms/com.google.android.gms.nearby.bootstrap.service.NearbyBootstrapService
pm $status com.google.android.gms/com.google.android.gms.nearby.connection.service.NearbyConnectionsAndroidService
pm $status com.google.android.gms/com.google.location.nearby.direct.service.NearbyDirectService
pm $status com.google.android.gms/com.google.android.gms.nearby.messages.service.NearbyMessagesService
pm $status com.google.android.gms/com.google.android.gms.update.SystemUpdateService
pm $status com.google.android.gms/com.google.android.gms.pay.gcmtask.PayGcmTaskService
pm $status com.google.android.gms/com.google.android.gms.pay.security.storagekey.service.StorageKeyCacheService
pm $status com.google.android.gms/com.google.android.gms.pay.notifications.PayNotificationService
pm $status com.google.android.gms/com.google.android.gms.people.sync.PeopleSyncService
pm $status com.google.android.gms/com.google.android.gms.people.service.bg.PeoplePeriodicSyncGcmTask
pm $status com.google.android.gms/com.google.android.gms.people.service.bg.PeopleOneoffSyncGcmTask
pm $status com.google.android.gms/com.google.android.gms.plus.service.OfflineActionSyncAdapterService
pm $status com.google.android.gms/com.google.android.gms.reminders.sync.RemindersSyncService
pm $status com.google.android.gms/com.google.android.gms.tapandpay.hce.service.TpHceService
pm $status com.google.android.gms/com.google.android.gms.usagereporting.service.UsageReportingIntentService
pm $status com.google.android.gms/com.google.android.gms.wearable.service.WearableService
pm $status com.google.android.gms/com.google.android.gms.wearable.service.WearableControlService
pm $status com.google.android.gms/com.google.android.gms.wearable.node.bluetooth.BluetoothServerService
pm $status com.google.android.gms/com.google.android.gms.wearable.node.emulator.NetworkConnectionService
pm $status com.google.android.gms/com.google.android.gms.westworld.WestworldService
pm $status com.google.android.gms/com.google.android.gms.chimera.container.FileApkChimeraService\$FileApkService
pm $status com.google.android.gms/com.google.android.gms.chimera.GmsApiServiceNoInstantApps
pm $status com.google.android.gms/com.google.android.gms.chimera.PersistentApiServiceNoInstantApps
pm $status com.google.android.gms/com.google.android.gms.chimera.UiApiServiceNoInstantApps
pm $status com.google.android.gms/com.google.android.gms.measurement.AppMeasurementService
pm $status com.google.android.gms/com.google.android.gms.measurement.AppMeasurementJobService
pm $status com.google.android.gsf/com.google.android.gsf.subscribedfeeds.SubscribedFeedsSyncAdapterService
pm $status com.mi.android.globalFileexplorer/com.google.firebase.messaging.FirebaseMessagingService
pm $status com.mi.android.globalFileexplorer/com.google.android.gms.measurement.AppMeasurementService
pm $status com.android.inputmethod.latin/com.android.inputmethod.latin.spellcheck.AndroidSpellCheckerService
pm $status com.android.inputmethod.latin/com.android.inputmethod.dictionarypack.DictionaryService
pm $status com.google.android.calendar/com.google.android.calendar.widget.CalendarAppWidgetService
pm $status com.google.android.calendar/com.google.android.syncadapters.calendar.CalendarSyncAdapterService
pm $status com.google.android.syncadapters.calendar/com.google.android.syncadapters.calendar.CalendarSyncAdapterService
pm $status com.asus.stitchimage/com.google.android.gms.measurement.AppMeasurementService
pm $status com.google.android.GoogleCamera/com.google.android.apps.camera.app.silentfeedback.SilentFeedbackService
pm $status com.android.traceur/com.android.traceur.QsService
# End
