#!/system/bin/sh

# Since we gonna check lots of files existence
function nex () {
	if [ -e $1 -a -w $1 ]; then
	echo $2 > $1
	fi
}

# drop ram cache ( clear pagecache, dentries, and inodes )
nex /proc/sys/vm/drop_caches 3

# Kernel
nex /proc/sys/kernel/sched_child_runs_first 0
nex /proc/sys/kernel/timer_migration 0
nex /proc/sys/kernel/perf_cpu_time_max_percent 15
nex /proc/sys/kernel/sched_min_granularity_ns 3000000
nex /proc/sys/kernel/sched_migration_cost_ns 1000000
nex /proc/sys/kernel/sched_nr_migrate 128
nex /proc/sys/kernel/sched_autogroup_enabled 0

# Fs
nex /proc/sys/fs/lease-break-time 5

# VM
nex /proc/sys/vm/stat_interval 1
nex /proc/sys/vm/vfs_cache_pressure 75
nex /proc/sys/vm/swappiness 100

# Stuneboost
nex /dev/stune/top-app/schedtune.boost 6
nex /dev/stune/foreground/schedtune.boost 1
nex /dev/stune/top-app/schedtune.prefer_idle 1

# EAS
nex /proc/sys/kernel/sched_energy_aware 0

# CPU
nex /sys/module/cpu_input_boost/parameters/input_boost_duration 128

# spi CRC
nex /sys/module/mmc_core/parameters/use_spi_crc 0

# GPU
nex /sys/class/kgsl/kgsl-3d0/devfreq/adrenoboost 3

# adreno idler
if [ -e /sys/class/kgsl/kgsl-3d0/devfreq/adrenoboost ]; then
nex /sys/module/adreno_idler/parameters/adreno_idler_active 0
else
nex /sys/module/adreno_idler/parameters/adreno_idler_active 1
nex /sys/module/adreno_idler/parameters/adreno_idler_downdifferential 64
nex /sys/module/adreno_idler/parameters/adreno_idler_idlewait 64
nex /sys/module/adreno_idler/parameters/adreno_idler_idleworkload 64
fi

nex /sys/class/kgsl/kgsl-3d0/devfreq/polling_interval 4

nex /sys/class/kgsl/kgsl-3d0/throttling 0
nex /sys/class/kgsl/kgsl-3d0/force_clk_on 1
nex /sys/class/kgsl/kgsl-3d0/force_bus_on 1
nex /sys/class/kgsl/kgsl-3d0/force_rail_on 1
nex /sys/class/kgsl/kgsl-3d0/force_no_nap 1
nex /sys/class/kgsl/kgsl-3d0/bus_split 0

nex /sys/class/kgsl/kgsl-3d0/dispatch/inflight 25
nex /sys/class/kgsl/kgsl-3d0/dispatch/inflight_low_latency 5

# Schedutil Bess
nex /sys/devices/system/cpu/cpu0/cpufreq/schedutil/down_rate_limit_us 40000
nex /sys/devices/system/cpu/cpu4/cpufreq/schedutil/down_rate_limit_us 30000
nex /sys/devices/system/cpu/cpu0/cpufreq/schedutil/iowait_boost_enable 1
nex /sys/devices/system/cpu/cpu4/cpufreq/schedutil/iowait_boost_enable 1
nex /sys/devices/system/cpu/cpu0/cpufreq/schedutil/up_rate_limit_us 500
nex /sys/devices/system/cpu/cpu4/cpufreq/schedutil/up_rate_limit_us 500

# Block
for queue in /sys/block/*/queue
do
echo 64 > "${queue}"/nr_requests
echo 2 > "${queue}"/rq_affinity
echo 2 > "${queue}"/nomerges
done

# Only clear pagecache
nex /proc/sys/vm/drop_caches 1

# Notify nexus deamon know that we're done here
resetprop nex.profile 2
sed -i '/nex.profile=/s/.*/nex.profile=2/' /data/adb/modules/nexus/system.prop

am kill-all

