#!/system/bin/sh

# Since we gonna check lots of files existence 
# and change its perms to rw-r-r (0644)
function nex () {
	if [ -e $1 ]; then
	chmod 0644 $1
	echo $2 > $1
	fi
}

# Kernel
nex /proc/sys/kernel/sched_child_runs_first 1
nex /proc/sys/kernel/timer_migration 1
nex /proc/sys/kernel/perf_cpu_time_max_percent 90
nex /proc/sys/kernel/sched_min_granularity_ns 1250000
nex /proc/sys/kernel/sched_migration_cost_ns 500000

# VM
nex /proc/sys/vm/stat_interval 60

# Stuneboost
nex /dev/stune/top-app/schedtune.boost 1
nex /dev/stune/foreground/schedtune.boost 0
nex /dev/stune/top-app/schedtune.prefer_idle 0

# GPU
nex /sys/class/kgsl/kgsl-3d0/devfreq/adrenoboost 0

nex /sys/class/kgsl/kgsl-3d0/throttling 1
nex /sys/class/kgsl/kgsl-3d0/force_clk_on 0
nex /sys/class/kgsl/kgsl-3d0/force_bus_on 0
nex /sys/class/kgsl/kgsl-3d0/force_rail_on 0
nex /sys/class/kgsl/kgsl-3d0/force_no_nap 0
nex /sys/class/kgsl/kgsl-3d0/bus_split 1

# Schedutil Bess
nex /sys/devices/system/cpu/cpu0/cpufreq/schedutil/down_rate_limit_us 2000
nex /sys/devices/system/cpu/cpu4/cpufreq/schedutil/down_rate_limit_us 2000
nex /sys/devices/system/cpu/cpu0/cpufreq/schedutil/iowait_boost_enable 0
nex /sys/devices/system/cpu/cpu4/cpufreq/schedutil/iowait_boost_enable 0
nex /sys/devices/system/cpu/cpu0/cpufreq/schedutil/up_rate_limit_us 500
nex /sys/devices/system/cpu/cpu4/cpufreq/schedutil/up_rate_limit_us 500

# Notify nexus deamon know that we're done here
resetprop nex.profile 0
sed -i '/nex.profile=/s/.*/nex.profile=0/' /data/adb/modules/nexus/system.prop

