#!/system/bin/sh

# Since we gonna check lots of files existence 
# and change its perms to rw-r-r (0644)
function nex () {
	if [ -e $1 ]; then
	chmod 0644 $1
	echo $2 > $1
	fi
}

# Kernel
nex /proc/sys/kernel/sched_boost 0
nex /proc/sys/kernel/panic 0
nex /proc/sys/kernel/panic_on_oops 0
nex /proc/sys/kernel/printk "0 0 0 0"
nex /proc/sys/kernel/sched_tunable_scaling
nex /proc/sys/kernel/compat-log 0
nex /proc/sys/kernel/sched_cfs_boost 0

# VM 
nex /proc/sys/vm/oom_kill_allocating_task 0
nex /proc/sys/vm/page-cluster 0
nex /proc/sys/vm/extfrag_threshold 750

# cpuset
nex /dev/cpuset/audio-app/cpus "0-3"
nex /dev/cpuset/foreground/cpus "0-3,6-7"
nex /dev/cpuset/background/cpus "0-1"

# disable adreno idler
nex /sys/module/adreno_idler/parameters/adreno_idler_active 0

# disable cpu boost
nex /sys/module/cpu_boost/parameters/input_boost_ms 0

# cpu input boost
nex /sys/module/cpu_input_boost/parameters/wake_boost_duration 256

# touch boost
nex /sys/power/pnpmgr/touch_boost 0
nex /sys/module/msm_performance/parameters/touchboost 0

# Disabled Exception-trace
nex /proc/sys/debug/exception-trace 0

# Disable some kernel debugging
for i in /sys/module/*/parameters/debug_mask
do 
echo 0 > $i
done

for i in /sys/module/*/parameters/debug_level 
do 
echo 0 > $i
done

# Disable some more debugging
nex /sys/module/debug/parameters/enable_event_log 0
nex /sys/module/usb_bam/parameters/enable_event_log 0
nex /sys/module/printk/parameters/console_suspend Y
nex /sys/module/printk/parameters/ignore_loglevel Y
nex /sys/module/printk/parameters/time N
nex /sys/module/bluetooth/parameters/disable_ertm Y
nex /sys/module/bluetooth/parameters/disable_esco Y
nex /sys/module/hid_apple/parameters/fnmode 0
nex /sys/module/ip6_tunnel/parameters/log_ecn_error N
nex /sys/module/sit/parameters/log_ecn_error N
nex /sys/module/hid/parameters/ignore_special_drivers 0
nex /sys/module/hid_magicmouse/parameters/emulate_3button N
nex /sys/module/hid_magicmouse/parameters/emulate_scroll_wheel N
nex /sys/module/hid_magicmouse/parameters/scroll_speed 0
nex /sys/module/service_locator/parameters/enable 0
nex /sys/module/subsystem_restart/parameters/disable_restart_work 1
nex /sys/module/rmnet_data/parameters/rmnet_data_log_level 0
nex /sys/module/diagchar/parameters/diag_mask_clear_param 0
nex /sys/module/hid/parameters/ignore_special_drivers 1
nex /sys/module/icnss/parameters/dynamic_feature_mask 0
nex /sys/module/ppp_generic/parameters/mp_protocol_compress 0

# TCP
nex /proc/sys/net/ipv4/tcp_ecn 1

