#!/system/bin/sh

# Since we gonna check lots of files existence 
# and change its perms to rw-r-r (0644)
function nex () {
	if [ -e $1 ]; then
	chmod 0644 $1
	echo $2 > $1
	fi
}

# Kernel
nex /proc/sys/kernel/sched_boost 0
nex /proc/sys/kernel/panic 0
nex /proc/sys/kernel/panic_on_oops 0
nex /proc/sys/kernel/printk "0 0 0 0"
nex /proc/sys/kernel/sched_tunable_scaling
nex /proc/sys/kernel/compat-log 0
nex /proc/sys/kernel/sched_cfs_boost 0

# VM 
nex /proc/sys/vm/oom_kill_allocating_task 0
nex /proc/sys/vm/page-cluster 0

# cpuset
nex /dev/cpuset/audio-app/cpus "0-3"
nex /dev/cpuset/foreground/cpus "0-3,6-7"
nex /dev/cpuset/background/cpus "0-1"

# disable adreno idler
nex /sys/module/adreno_idler/parameters/adreno_idler_active 0
