#!/system/bin/sh

# Since we gonna check lots of files existence 
# and change its perms to rw-r-r (0644)
function nex () {
	if [ -e $1 ]; then
	chmod 0644 $1
	echo $2 > $1
	fi
}

# Kernel
nex /proc/sys/kernel/sched_child_runs_first 0
nex /proc/sys/kernel/timer_migration 1
nex /proc/sys/kernel/perf_cpu_time_max_percent 0
nex /proc/sys/kernel/sched_min_granularity_ns 3000000
nex /proc/sys/kernel/sched_migration_cost_ns 1000000
nex /proc/sys/kernel/sched_nr_migrate 128

# VM
nex /proc/sys/vm/stat_interval 1
nex /proc/sys/vm/vfs_cache_pressure 75
nex /proc/sys/vm/swappiness 100

# Stuneboost
nex /dev/stune/top-app/schedtune.boost 6
nex /dev/stune/foreground/schedtune.boost 1
nex /dev/stune/top-app/schedtune.prefer_idle 1

# CPU
nex /sys/module/cpu_input_boost/parameters/input_boost_duration 128

# spi CRC
nex /sys/module/mmc_core/parameters/use_spi_crc 0

# GPU
nex /sys/class/kgsl/kgsl-3d0/devfreq/adrenoboost 3

nex /sys/class/kgsl/kgsl-3d0/throttling 0
nex /sys/class/kgsl/kgsl-3d0/force_clk_on 1
nex /sys/class/kgsl/kgsl-3d0/force_bus_on 1
nex /sys/class/kgsl/kgsl-3d0/force_rail_on 1
nex /sys/class/kgsl/kgsl-3d0/force_no_nap 1
nex /sys/class/kgsl/kgsl-3d0/bus_split 0

nex /sys/class/kgsl/kgsl-3d0/dispatch/inflight 25
nex /sys/class/kgsl/kgsl-3d0/dispatch/inflight_low_latency 5

# Schedutil Bess
nex /sys/devices/system/cpu/cpu0/cpufreq/schedutil/down_rate_limit_us 40000
nex /sys/devices/system/cpu/cpu4/cpufreq/schedutil/down_rate_limit_us 30000
nex /sys/devices/system/cpu/cpu0/cpufreq/schedutil/iowait_boost_enable 1
nex /sys/devices/system/cpu/cpu4/cpufreq/schedutil/iowait_boost_enable 1
nex /sys/devices/system/cpu/cpu0/cpufreq/schedutil/up_rate_limit_us 500
nex /sys/devices/system/cpu/cpu4/cpufreq/schedutil/up_rate_limit_us 500

# Notify nexus deamon know that we're done here
resetprop nex.profile 2
sed -i '/nex.profile=/s/.*/nex.profile=2/' /data/adb/modules/nexus/system.prop

am kill-all

