name: NexusTweak

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: z4nyx/docker:latest

    steps:
      - uses: actions/checkout@v2
      - name: Nexus Tweak
        run: bash build.sh
        env:
           token: ${{ secrets.TOKEN }}
           chat_id: ${{ secrets.CHAT_ID }}
           buildNo: ${{ github.RUN_NUMBER }}
           gh_token: ${{ secrets.GH_TOKEN }}
